/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * NOTE: Normally generated by `npx convex dev`; committed for offline development.
 * `anyApi` resolves function references dynamically at runtime.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
